sudo: required
services:
  - docker

before_install:
  - docker build -t jaiswal91/docker-react -f Dockerfile.dev .

script:
  - docker run jaiswal91/docker-react npm run test -- --coverage

